`timescale 1ns/1ps

/*
 * Frank Ouma
 * Project 07 - Custom Descriptor-Ring DMA Engine + Linux Driver
 *
 * DMA interrupt controller.
 *
 * IRQ_STATUS mapping:
 *
 *   bit 0 - TX completion
 *   bit 1 - RX completion
 *   bit 2 - TX error
 *   bit 3 - RX error
 *
 * Interrupt causes are latched until explicitly cleared by software.
 *
 * Clear semantics are write-one-to-clear.
 *
 * If an event and clear for the same cause occur on the same clock,
 * the new event wins. This prevents software acknowledgement from
 * accidentally losing a newly arriving interrupt.
 */

module dma_irq_controller (
    input  logic       clk,
    input  logic       aresetn,

    input  logic       tx_completion_event,
    input  logic       rx_completion_event,
    input  logic       tx_error_event,
    input  logic       rx_error_event,

    /*
     * Software-visible interrupt enable mask.
     */
    input  logic [3:0] irq_enable,

    /*
     * One-cycle W1C clear mask generated by the AXI-Lite register
     * block when software writes IRQ_STATUS.
     */
    input  logic [3:0] irq_clear,

    output logic [3:0] irq_status,

    /*
     * PL -> PS interrupt output.
     */
    output logic       irq
);

    logic [3:0] event_set;

    always_comb begin

        event_set[0] = tx_completion_event;
        event_set[1] = rx_completion_event;
        event_set[2] = tx_error_event;
        event_set[3] = rx_error_event;

        irq =
            |(irq_status & irq_enable);

    end

    always_ff @(posedge clk) begin

        if (!aresetn) begin

            irq_status <=
                4'b0000;

        end
        else begin

            /*
             * Set-dominant interrupt update:
             *
             *   1. clear acknowledged pending causes
             *   2. OR in any events occurring on this same cycle
             *
             * Therefore:
             *
             *   clear=1, event=1 -> resulting status remains 1
             */
            irq_status <=
                (irq_status & ~irq_clear) |
                event_set;

        end

    end

endmodule
