# ============================================================================
# Project 06 - Streaming DSP Accelerator SoC
# Full ZCU104 synthesis + place-and-route
#
# Author: Frank Ouma
#
# IMPORTANT:
#   This stops after route_design.
#   Bitstream generation is deliberately deferred until implementation
#   timing / DRC / CDC are audited.
# ============================================================================

set script_dir [file dirname [file normalize [info script]]]
set root       [file normalize [file join $script_dir ..]]

set project_file \
    "$root/build/vivado_soc/project06_soc.xpr"

set reports \
    "$root/reports"

file mkdir $reports

puts ""
puts "============================================================"
puts " PROJECT06 FULL SOC IMPLEMENTATION"
puts "============================================================"

open_project $project_file

# Explicit top-level generated by make_wrapper.
set_property top system_wrapper [current_fileset]

update_compile_order -fileset sources_1

puts ""
puts "Top module : [get_property TOP [current_fileset]]"
puts "Part       : [get_property PART [current_project]]"
puts "Board      : [get_property BOARD_PART [current_project]]"

# ============================================================================
# SYNTHESIS
# ============================================================================

puts ""
puts "============================================================"
puts " SYNTHESIS"
puts "============================================================"

reset_run synth_1

launch_runs synth_1 \
    -jobs 12

wait_on_run synth_1

set synth_status \
    [get_property STATUS [get_runs synth_1]]

puts "SYNTHESIS STATUS: $synth_status"

if {![string match "*Complete*" $synth_status]} {
    error "PROJECT06 synthesis did not complete successfully"
}

open_run synth_1

report_utilization \
    -file "$reports/soc_synthesis_utilization.rpt"

report_utilization \
    -hierarchical \
    -file "$reports/soc_synthesis_utilization_hierarchical.rpt"

report_timing_summary \
    -delay_type min_max \
    -report_unconstrained \
    -check_timing_verbose \
    -max_paths 50 \
    -file "$reports/soc_synthesis_timing_summary.rpt"

report_drc \
    -file "$reports/soc_synthesis_drc.rpt"

report_methodology \
    -file "$reports/soc_synthesis_methodology.rpt"

puts ""
puts "SOC SYNTHESIS: PASS"

# ============================================================================
# IMPLEMENTATION THROUGH ROUTE_DESIGN
# ============================================================================

puts ""
puts "============================================================"
puts " IMPLEMENTATION"
puts "============================================================"

reset_run impl_1

launch_runs impl_1 \
    -to_step route_design \
    -jobs 12

wait_on_run impl_1

set impl_status \
    [get_property STATUS [get_runs impl_1]]

puts "IMPLEMENTATION STATUS: $impl_status"

if {![string match "*Complete*" $impl_status]} {
    error "PROJECT06 implementation did not complete successfully"
}

open_run impl_1

# ============================================================================
# FINAL PHYSICAL REPORTS
# ============================================================================

report_utilization \
    -file "$reports/soc_implementation_utilization.rpt"

report_utilization \
    -hierarchical \
    -file "$reports/soc_implementation_utilization_hierarchical.rpt"

report_timing_summary \
    -delay_type min_max \
    -report_unconstrained \
    -check_timing_verbose \
    -max_paths 100 \
    -file "$reports/soc_implementation_timing_summary.rpt"

report_drc \
    -file "$reports/soc_implementation_drc.rpt"

report_methodology \
    -file "$reports/soc_implementation_methodology.rpt"

report_route_status \
    -file "$reports/soc_route_status.rpt"

report_clock_interaction \
    -file "$reports/soc_clock_interaction.rpt"

report_cdc \
    -details \
    -file "$reports/soc_cdc.rpt"

check_timing \
    -verbose \
    -file "$reports/soc_check_timing.rpt"

puts ""
puts "============================================================"
puts " PROJECT06 ROUTED SOC IMPLEMENTATION COMPLETE"
puts "============================================================"
puts "Top:"
puts "  [get_property TOP [current_fileset]]"
puts ""
puts "Implementation status:"
puts "  $impl_status"
puts ""
puts "Bitstream:"
puts "  NOT GENERATED YET"
puts ""
puts "Next:"
puts "  Audit timing / DRC / CDC before write_bitstream"
puts "============================================================"

close_project
exit
