// =============================================================================
// spi_master.sv — Generic SPI master, Mode 0 (CPOL=0, CPHA=0)
//
// Parameterised for system clock frequency, SPI frequency, and transfer width.
// Data is shifted out MSB-first on MOSI; MISO is sampled on rising SCLK edges.
// A single-cycle start pulse begins a transaction; done pulses for one cycle
// on completion and busy is asserted for the full duration of the transfer.
//
// SCLK is generated by dividing the system clock:
//   half_period = CLK_FREQ / (2 * SPI_FREQ)   [integer division]
// SCLK toggles every half_period system clock cycles.
//
// FSM states:
//   IDLE     — cs_n high, sclk low, waiting for start
//   TRANSFER — clocking DATA_WIDTH bits; MISO sampled on rising SCLK,
//              MOSI updated on falling SCLK
//   DONE     — cs_n deasserted, done pulsed, data_out latched
// =============================================================================

module spi_master #(
    parameter int CLK_FREQ   = 100_000_000,
    parameter int SPI_FREQ   =   1_000_000,
    parameter int DATA_WIDTH = 16
) (
    input  logic                   clk,
    input  logic                   rst_n,

    input  logic                   start,
    input  logic [DATA_WIDTH-1:0]  data_in,
    input  logic                   miso,

    output logic                   sclk,
    output logic                   mosi,
    output logic                   cs_n,
    output logic [DATA_WIDTH-1:0]  data_out,
    output logic                   done,
    output logic                   busy
);

    localparam int HALF_PERIOD = CLK_FREQ / (2 * SPI_FREQ);
    localparam int CNT_W       = $clog2(HALF_PERIOD);
    localparam int BIT_CNT_W   = $clog2(DATA_WIDTH) + 1;  // holds 0..DATA_WIDTH

    typedef enum logic [1:0] { IDLE, TRANSFER, DONE } state_t;

    state_t                   state;
    logic [CNT_W-1:0]         clk_cnt;
    logic [BIT_CNT_W-1:0]     bit_cnt;   // decremented on each rising SCLK edge
    logic [DATA_WIDTH-1:0]    tx_reg;
    logic [DATA_WIDTH-1:0]    rx_reg;
    logic                     sclk_r;

    assign sclk = sclk_r;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= IDLE;
            clk_cnt  <= '0;
            bit_cnt  <= '0;
            tx_reg   <= '0;
            rx_reg   <= '0;
            sclk_r   <= 1'b0;
            cs_n     <= 1'b1;
            mosi     <= 1'b0;
            done     <= 1'b0;
            busy     <= 1'b0;
            data_out <= '0;
        end else begin
            done <= 1'b0;  // default: one-cycle pulse only

            case (state)

                IDLE: begin
                    cs_n   <= 1'b1;
                    sclk_r <= 1'b0;
                    if (start) begin
                        tx_reg  <= data_in;
                        rx_reg  <= '0;
                        bit_cnt <= BIT_CNT_W'(DATA_WIDTH);
                        clk_cnt <= '0;
                        cs_n    <= 1'b0;
                        mosi    <= data_in[DATA_WIDTH-1];  // pre-drive MSB
                        busy    <= 1'b1;
                        state   <= TRANSFER;
                    end
                end

                TRANSFER: begin
                    if (clk_cnt == CNT_W'(HALF_PERIOD - 1)) begin
                        clk_cnt <= '0;
                        sclk_r  <= ~sclk_r;

                        if (!sclk_r) begin
                            // sclk rising edge — sample MISO, shift into RX
                            rx_reg  <= {rx_reg[DATA_WIDTH-2:0], miso};
                            bit_cnt <= bit_cnt - 1'b1;
                        end else begin
                            // sclk falling edge — update MOSI or finish
                            if (bit_cnt == '0) begin
                                state <= DONE;
                            end else begin
                                tx_reg <= {tx_reg[DATA_WIDTH-2:0], 1'b0};
                                mosi   <= tx_reg[DATA_WIDTH-2];
                            end
                        end
                    end else begin
                        clk_cnt <= clk_cnt + 1'b1;
                    end
                end

                DONE: begin
                    cs_n     <= 1'b1;
                    sclk_r   <= 1'b0;
                    mosi     <= 1'b0;
                    data_out <= rx_reg;
                    done     <= 1'b1;
                    busy     <= 1'b0;
                    state    <= IDLE;
                end

                default: state <= IDLE;

            endcase
        end
    end

endmodule
