`timescale 1ns/1ps

// Project 06 - Streaming DSP Accelerator SoC
// 32-tap fully parallel, pipelined AXI4-Stream FIR
//
// Author: Frank Ouma
// FPGA / SoC / Digital Hardware Engineering
//
// Numerical contract:
//   input       : signed Q1.15
//   coefficient : signed Q1.15
//   product     : signed 32-bit Q2.30
//   accumulator : signed 37-bit
//   output      : signed Q1.15
//   rounding    : nearest, ties away from zero
//   overflow    : saturation
//
// Architectural target:
//   initiation interval = 1 accepted sample / clock

module fir32_axis (
    input  logic        aclk,
    input  logic        aresetn,

    input  logic [15:0] s_axis_tdata,
    input  logic        s_axis_tvalid,
    output logic        s_axis_tready,
    input  logic        s_axis_tlast,

    output logic [15:0] m_axis_tdata,
    output logic        m_axis_tvalid,
    input  logic        m_axis_tready,
    output logic        m_axis_tlast
);

    // Previous 31 accepted samples.
    logic signed [15:0] history [0:30];

    // Pipeline arithmetic stages.
    logic signed [31:0] prod_s0 [0:31];
    logic signed [32:0] sum_s1  [0:15];
    logic signed [33:0] sum_s2  [0:7];
    logic signed [34:0] sum_s3  [0:3];
    logic signed [35:0] sum_s4  [0:1];
    logic signed [36:0] sum_s5;

    logic signed [15:0] quant_s6;

    logic valid_s0;
    logic valid_s1;
    logic valid_s2;
    logic valid_s3;
    logic valid_s4;
    logic valid_s5;
    logic valid_s6;

    logic last_s0;
    logic last_s1;
    logic last_s2;
    logic last_s3;
    logic last_s4;
    logic last_s5;
    logic last_s6;

    logic advance;

    integer i;

    // ------------------------------------------------------------------
    // Frozen 32-tap Q1.15 coefficient set generated by the authoritative
    // Project06 Python reference model.
    // ------------------------------------------------------------------

    function automatic logic signed [15:0] coeff_at(input integer index);
        begin
            case (index)
                 0: coeff_at = 16'shFFEF;
                 1: coeff_at = 16'sh0014;
                 2: coeff_at = 16'sh0049;
                 3: coeff_at = 16'sh0087;
                 4: coeff_at = 16'sh00A4;
                 5: coeff_at = 16'sh005B;
                 6: coeff_at = 16'shFF7F;
                 7: coeff_at = 16'shFE2E;
                 8: coeff_at = 16'shFCF1;
                 9: coeff_at = 16'shFCAE;
                10: coeff_at = 16'shFE4D;
                11: coeff_at = 16'sh024C;
                12: coeff_at = 16'sh085D;
                13: coeff_at = 16'sh0F57;
                14: coeff_at = 16'sh157D;
                15: coeff_at = 16'sh1918;
                16: coeff_at = 16'sh1918;
                17: coeff_at = 16'sh157D;
                18: coeff_at = 16'sh0F57;
                19: coeff_at = 16'sh085D;
                20: coeff_at = 16'sh024C;
                21: coeff_at = 16'shFE4D;
                22: coeff_at = 16'shFCAE;
                23: coeff_at = 16'shFCF1;
                24: coeff_at = 16'shFE2E;
                25: coeff_at = 16'shFF7F;
                26: coeff_at = 16'sh005B;
                27: coeff_at = 16'sh00A4;
                28: coeff_at = 16'sh0087;
                29: coeff_at = 16'sh0049;
                30: coeff_at = 16'sh0014;
                31: coeff_at = 16'shFFEF;
                default: coeff_at = 16'sd0;
            endcase
        end
    endfunction

    // ------------------------------------------------------------------
    // Q2.30 accumulator -> Q1.15
    // Round to nearest, ties away from zero, then saturate.
    // ------------------------------------------------------------------

    function automatic logic signed [15:0]
        quantize_q15(input logic signed [36:0] acc);

        logic signed [37:0] extended;
        logic signed [37:0] magnitude;
        logic signed [37:0] rounded;

        begin
            extended = {acc[36], acc};

            if (extended >= 0) begin
                rounded =
                    (extended + 38'sd16384) >>> 15;
            end
            else begin
                magnitude = -extended;
                rounded =
                    -((magnitude + 38'sd16384) >>> 15);
            end

            if (rounded > 38'sd32767)
                quantize_q15 = 16'sh7FFF;
            else if (rounded < -38'sd32768)
                quantize_q15 = 16'sh8000;
            else
                quantize_q15 = rounded[15:0];
        end
    endfunction

    // Whole pipeline is stallable.
    //
    // When the output is blocked, every arithmetic stage freezes.
    // Therefore data, validity and TLAST remain aligned.
    assign advance =
        (~valid_s6) | m_axis_tready;

    assign s_axis_tready =
        aresetn && advance;

    assign m_axis_tdata  = quant_s6;
    assign m_axis_tvalid = valid_s6;
    assign m_axis_tlast  = last_s6;

    always_ff @(posedge aclk) begin

        if (!aresetn) begin

            valid_s0 <= 1'b0;
            valid_s1 <= 1'b0;
            valid_s2 <= 1'b0;
            valid_s3 <= 1'b0;
            valid_s4 <= 1'b0;
            valid_s5 <= 1'b0;
            valid_s6 <= 1'b0;

            last_s0 <= 1'b0;
            last_s1 <= 1'b0;
            last_s2 <= 1'b0;
            last_s3 <= 1'b0;
            last_s4 <= 1'b0;
            last_s5 <= 1'b0;
            last_s6 <= 1'b0;

            quant_s6 <= '0;
            sum_s5   <= '0;

            for (i = 0; i < 31; i = i + 1)
                history[i] <= '0;

            for (i = 0; i < 32; i = i + 1)
                prod_s0[i] <= '0;

            for (i = 0; i < 16; i = i + 1)
                sum_s1[i] <= '0;

            for (i = 0; i < 8; i = i + 1)
                sum_s2[i] <= '0;

            for (i = 0; i < 4; i = i + 1)
                sum_s3[i] <= '0;

            for (i = 0; i < 2; i = i + 1)
                sum_s4[i] <= '0;

        end
        else if (advance) begin

            // ----------------------------------------------------------
            // Validity and TLAST pipeline
            // ----------------------------------------------------------

            valid_s6 <= valid_s5;
            valid_s5 <= valid_s4;
            valid_s4 <= valid_s3;
            valid_s3 <= valid_s2;
            valid_s2 <= valid_s1;
            valid_s1 <= valid_s0;

            valid_s0 <= s_axis_tvalid && s_axis_tready;

            last_s6 <= last_s5;
            last_s5 <= last_s4;
            last_s4 <= last_s3;
            last_s3 <= last_s2;
            last_s2 <= last_s1;
            last_s1 <= last_s0;
            last_s0 <= s_axis_tlast;

            // ----------------------------------------------------------
            // Stage 6 - quantization
            // ----------------------------------------------------------

            if (valid_s5)
                quant_s6 <= quantize_q15(sum_s5);

            // ----------------------------------------------------------
            // Stage 5 - final 37-bit accumulation
            // ----------------------------------------------------------

            if (valid_s4) begin
                sum_s5 <=
                    $signed({sum_s4[0][35], sum_s4[0]}) +
                    $signed({sum_s4[1][35], sum_s4[1]});
            end

            // ----------------------------------------------------------
            // Stage 4 - 4 -> 2
            // ----------------------------------------------------------

            if (valid_s3) begin
                for (i = 0; i < 2; i = i + 1) begin
                    sum_s4[i] <=
                        $signed({
                            sum_s3[2*i][34],
                            sum_s3[2*i]
                        }) +
                        $signed({
                            sum_s3[(2*i)+1][34],
                            sum_s3[(2*i)+1]
                        });
                end
            end

            // ----------------------------------------------------------
            // Stage 3 - 8 -> 4
            // ----------------------------------------------------------

            if (valid_s2) begin
                for (i = 0; i < 4; i = i + 1) begin
                    sum_s3[i] <=
                        $signed({
                            sum_s2[2*i][33],
                            sum_s2[2*i]
                        }) +
                        $signed({
                            sum_s2[(2*i)+1][33],
                            sum_s2[(2*i)+1]
                        });
                end
            end

            // ----------------------------------------------------------
            // Stage 2 - 16 -> 8
            // ----------------------------------------------------------

            if (valid_s1) begin
                for (i = 0; i < 8; i = i + 1) begin
                    sum_s2[i] <=
                        $signed({
                            sum_s1[2*i][32],
                            sum_s1[2*i]
                        }) +
                        $signed({
                            sum_s1[(2*i)+1][32],
                            sum_s1[(2*i)+1]
                        });
                end
            end

            // ----------------------------------------------------------
            // Stage 1 - 32 -> 16
            // ----------------------------------------------------------

            if (valid_s0) begin
                for (i = 0; i < 16; i = i + 1) begin
                    sum_s1[i] <=
                        $signed({
                            prod_s0[2*i][31],
                            prod_s0[2*i]
                        }) +
                        $signed({
                            prod_s0[(2*i)+1][31],
                            prod_s0[(2*i)+1]
                        });
                end
            end

            // ----------------------------------------------------------
            // Stage 0 - 32 parallel multiplications
            //
            // Current sample is tap 0.
            // Stored history provides taps 1..31.
            // ----------------------------------------------------------

            if (s_axis_tvalid && s_axis_tready) begin

                prod_s0[0] <=
                    $signed(s_axis_tdata) *
                    $signed(coeff_at(0));

                for (i = 1; i < 32; i = i + 1) begin
                    prod_s0[i] <=
                        $signed(history[i-1]) *
                        $signed(coeff_at(i));
                end

                // Accepted samples only advance FIR history.
                for (i = 30; i > 0; i = i - 1)
                    history[i] <= history[i-1];

                history[0] <= $signed(s_axis_tdata);
            end
        end
    end

endmodule
